modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)

[[mods]] #mandatory
modId="timetolive" #mandatory
version="${version}"
displayName="Time to Live"
logoFile="logo.png" #optional
authors="Schauweg" #optional
description='''
This mod simply displays a countdown timer of the remaining time a TNT entity has left.
'''